apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Diplom
  annotations:
    github.com/project-slug: H1kkar1/Diplom

    'backstage.io/kubernetes-id': diplom
    'backstage.io/kubernetes-namespace': flux-system
    
    'fluxcd.io/namespace': flux-system
    'fluxcd.io/name': flux-system
spec:
  type: service
  lifecycle: unknown
  owner: H1KKAR1
