apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: diplom
  description: Demo application for testing Backstage integration
  labels:
    app: demo-app
  annotations:
    github.com/project-slug: H1KKAR1/Diplom

    'backstage.io/kubernetes-id': diplom
    'backstage.io/kubernetes-namespace': default
    'backstage.io/kubernetes-label-selector': 'backstage.io/kubernetes-id=diplom'

    'fluxcd.io/namespace': flux-system
    'fluxcd.io/kustomization': demo-app
    'weave.works/flux-kustomization': demo-app
spec:
  type: service
  lifecycle: unknown
  owner: H1KKAR1
  providesApis:
    - demo-app-api
