apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  namespace: python
  labels:
    app: python
    team: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
        team: python
    spec:
      containers:
      - name: app
        image: hikkari/test-python-service:576fa2053cb13d638f029fe68834abc34d2e8bc2
        ports:
        - containerPort: 8000
        env:
        - name: NAMESPACE
          value: python
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"